name: linkyou
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Icon-App-83.5x83.5@2x.png"

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.0.6
  flutter_cache_manager: ^3.0.0
  cached_network_image: ^3.3.1
  socket_io_client: ^2.0.3+1
  get_it: ^7.2.0
  swipe_cards: ^2.0.0+1
  dio: ^5.4.1
  intl: ^0.19.0
  flutter_widget_from_html: ^0.15.3
  webview_flutter: ^4.10.0
  photo_view: ^0.14.0
  
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/no_pet_avatar.png
    - assets/wellcomeTizer/welcome.png
    - assets/icons/Icon-App-83.5x83.5@2x.png
    - assets/logo/logo.png
    - assets/logo-blue/logo.png
    - assets/crown/crown.png
    - assets/about/nationality.png
    - assets/about/mission.png
    - assets/about/profession.png
    - assets/about/misbehavior.png
    - assets/about/robot.png
    - assets/about/surprise.png