name: linkyou
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1  
  http: ^1.2.1
  provider: ^6.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.6
  cached_network_image: ^3.3.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wellcomeTizer/welcome.png
    - assets/logo/logo.png
    - assets/logo-blue/logo.png
    - assets/crown/crown.png
    - assets/about/nationality.png
    - assets/about/mission.png
    - assets/about/profession.png
    - assets/about/misbehavior.png
    - assets/about/robot.png
    - assets/about/surprise.png